<a href="https://colab.research.google.com/github/akhilspillai003/Pytorch/blob/main/Python_maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [9]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [10]:
# Addtion
tensor_c = tensor_a + tensor_b
print(tensor_c)

tensor([ 6,  8, 10, 12])


In [11]:
#subtraction
tensor_d = tensor_a - tensor_b
print(tensor_d)

tensor([-4, -4, -4, -4])


In [12]:
#addtion Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [13]:
#subtration Longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [14]:
#multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [15]:
#multiplication longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [16]:
#divition
tensor_b / tensor_a

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [17]:
#divition longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [19]:
#Reminder modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [21]:
#reminder longhand
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [22]:
#Exponents/Powers longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [23]:
#Reassigning _
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [24]:
tensor_a


tensor([ 6,  8, 10, 12])